[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hothemt"
dynamic = ["version"]
authors = [
    {name = "Samuel James Bader", email = "samuel.james.bader@gmail.com"}
]
description = "Open-source HEMT thermal simulations"
readme = "README.md"
requires-python = ">=3.12,<3.15"
license = { file = "LICENSE.txt" }

# Known dependency constraints:
# - sfepy (as of 2026.2) uses load_module() which is targeted for removal in Python 3.15
# - sfepy uses a few deprecated pyparsing functions targeted for removal in pyparsing 4.0
# - sfepy uses setting shape on numpy array, which is deprecated since numpy 2.5
# Providing these constraints here and filtering the relevant warnings in pytest.ini

dependencies = [
    # for making the mesh
    "gmsh",

    # for solving the FEM
    "sfepy",

    # otherwise, sfepy gives warnings
    "jax", 

    # Used by multiproc
    "pandas",

    # required by sfepy but pinned here (see above constraints)
    "pyparsing>=3.2,<4.0",
    "numpy>=2.5,<2.7",

    # Unless specified explicitly, other dependencies may install
    # these packages e.g. only on Windows but not Linux, which means
    # the requirements.txt file will be different for Windows/Linux
    # which breaks the simple CI that checks whether requirements.txt
    # and pyproject.toml are consistent
    "colorama>=0.4.6,<1",
    "tzdata",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pip-tools"
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "hothemt.__version__"}

[project.scripts]
hhplot = "hothemt.cli:cli_vis"
