[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hothemt"
dynamic = ["version"]
authors = [
    {name = "Samuel James Bader", email = "samuel.james.bader@gmail.com"}
]
description = "Open-source HEMT thermal simulations"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE.txt" }

dependencies = [
    # for making the mesh
    "gmsh == 4.14.1",

    # for solving the FEM
    "sfepy == 2025.3",

    # Otherwise, sfepy gives warnings
    "jax == 0.7.2", 

    # pinned to prevent set_new_attribute error
    "pyvista == 0.45.3", 

    # Misc
    "pytest",
    "pandas"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "hothemt.__version__"}

[project.scripts]
hhplot = "hothemt.cli:cli_vis"
