[pytest]
filterwarnings =
    # These deprecation warnings are why we constrain pyparsing <4.0
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
    # These deprecation warnings are why we constrain numpy <2.7
    ignore:.*Setting the shape on a NumPy.*:DeprecationWarning
    # These deprecation warnings are why we constrain Python <3.15
    ignore:.*load_module.*:DeprecationWarning